"""DeepSeek Provider 配置。"""

from app.app_config.settings import (
    DEEPSEEK_API_KEY,
    DEEPSEEK_BASE_URL,
    DEEPSEEK_MAX_RETRIES,
    DEEPSEEK_MODEL_NAME,
    DEEPSEEK_STRICT_TOOL_BASE_URL,
    DEEPSEEK_TIMEOUT_SECONDS,
)


__all__ = [
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_BASE_URL",
    "DEEPSEEK_MAX_RETRIES",
    "DEEPSEEK_MODEL_NAME",
    "DEEPSEEK_STRICT_TOOL_BASE_URL",
    "DEEPSEEK_TIMEOUT_SECONDS",
]
